FROM cgr.dev/chainguard/python:latest-dev AS builder
USER root
RUN apk --no-cache add jq
USER nonroot
# other stuff ...

# Use a more minimal base image
FROM cgr.dev/chainguard/python:latest
# COPY --from=builder other stuff I built above...
COPY --from=builder /usr/bin/jq /usr/bin/jq
ENTRYPOINT ["/usr/bin/jq"]