FROM python:3.12

ENV LANG=C.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/app/venv/bin:$PATH"

WORKDIR /app

COPY app.py requirements.txt /app/
COPY templates/index.html /app/templates/

RUN apt update && \
    apt install -y libpq-dev libvshadow-utils && \
    python -m venv /app/venv && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENTRYPOINT [ "python", "app.py" ]