FROM cgr.dev/chainguard/python:latest-dev AS builder
USER root

# Install the packages into a root derived from the distroless image.
#
# This method temporarily installs bash because some packages require a shell
# to run postinstall scripts. In this case (and most cases) you could omit
# those lines.
COPY --from=cgr.dev/chainguard/python:latest / /base-chroot
RUN apk add --no-commit-hooks --no-cache --root /base-chroot bash-binsh \
  && apk add --no-cache --root /base-chroot jq \
  && apk del --no-commit-hooks --root /base-chroot bash-binsh

USER nonroot

# other stuff ...

# Use a more minimal base image
FROM cgr.dev/chainguard/python:latest
COPY --from=builder /base-chroot /
# COPY --from=builder other stuff I built above...
ENTRYPOINT ["/usr/bin/jq"]
