FROM cgr.dev/chainguard/python:latest-dev AS build

USER root
# Note we are copying from the non-dev image here, this needs to match the final image base
COPY --from=cgr.dev/chainguard/python:latest / /base-chroot
RUN apk add --no-cache --no-commit-hooks --root /base-chroot mariadb-connector-c-dev mariadb bash

FROM cgr.dev/chainguard/python:latest
# Copy over the apks prep'ed at the end of the build stage (no apk-add in this image)
COPY --from=build /base-chroot /